// GENERATED by make_sdicons.py from Phosphor Icons (Light), MIT — https://phosphoricons.com
// The icons the app uses, from the Phosphor-Light font bundled in assets/fonts (the phosphor_flutter
// package does not compile on Flutter 3.47). Thin, even strokes: SAMBA's delicate iconography.
import 'package:flutter/widgets.dart';

class SdIcons {
  SdIcons._();
  static const _f = 'PhosphorLight';
  static const arrowLeft = IconData(0xe058, fontFamily: _f);
  static const arrowsClockwise = IconData(0xe094, fontFamily: _f);
  static const article = IconData(0xe0a8, fontFamily: _f);
  static const broadcast = IconData(0xe0f2, fontFamily: _f);
  static const cameraRotate = IconData(0xe7a4, fontFamily: _f);
  static const caretDown = IconData(0xe136, fontFamily: _f);
  static const caretRight = IconData(0xe13a, fontFamily: _f);
  static const circle = IconData(0xe18a, fontFamily: _f);
  static const clipboardText = IconData(0xe198, fontFamily: _f);
  static const clockCounterClockwise = IconData(0xe1a0, fontFamily: _f);
  static const columns = IconData(0xe546, fontFamily: _f);
  static const copy = IconData(0xe1ca, fontFamily: _f);
  static const copySimple = IconData(0xe1cc, fontFamily: _f);
  static const desktop = IconData(0xe560, fontFamily: _f);
  static const deviceMobile = IconData(0xe1e0, fontFamily: _f);
  static const eye = IconData(0xe220, fontFamily: _f);
  static const flashlight = IconData(0xe246, fontFamily: _f);
  static const headphones = IconData(0xe2a6, fontFamily: _f);
  static const keyboard = IconData(0xe2d8, fontFamily: _f);
  static const lightningSlash = IconData(0xe2e0, fontFamily: _f);
  static const link = IconData(0xe2e2, fontFamily: _f);
  static const microphone = IconData(0xe326, fontFamily: _f);
  static const plugs = IconData(0xeb56, fontFamily: _f);
  static const plugsConnected = IconData(0xeb5a, fontFamily: _f);
  static const qrCode = IconData(0xe3e6, fontFamily: _f);
  static const record = IconData(0xe3ee, fontFamily: _f);
  static const scissors = IconData(0xeae0, fontFamily: _f);
  static const slidersHorizontal = IconData(0xe434, fontFamily: _f);
  static const sparkle = IconData(0xe6a2, fontFamily: _f);
  static const speakerSlash = IconData(0xe45a, fontFamily: _f);
  static const square = IconData(0xe45e, fontFamily: _f);
  static const squaresFour = IconData(0xe464, fontFamily: _f);
  static const stop = IconData(0xe46c, fontFamily: _f);
  static const videoCamera = IconData(0xe4da, fontFamily: _f);
  static const videoCameraSlash = IconData(0xe4dc, fontFamily: _f);
  static const waveform = IconData(0xe802, fontFamily: _f);
  static const wifiHigh = IconData(0xe4ea, fontFamily: _f);
  static const wifiMedium = IconData(0xe4ee, fontFamily: _f);
  static const wifiSlash = IconData(0xe4f2, fontFamily: _f);
  static const x = IconData(0xe4f6, fontFamily: _f);
}
